name: MAX Price Watcher

on:
  schedule:
    - cron: "*/5 * * * *"   # 每 5 分鐘自動跑
  workflow_dispatch:        # 也支援手動測試

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: maxmoneynet-bot
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run bot
        env:
          WEBHOOK: ${{ secrets.WEBHOOK }}   # ← 從 Secrets 注入給程式
        run: python money.py
